### ISSUE TITLE
Override with system environment variable not working

### ISSUE THREAD

**Issue by AshleyHow** [lcoulet/windows_AutoLogoff#2]
Great program! I'm having a little issue -

If I create a system environment variable of AUTOLOGOFF_NB_IDLE_MINUTES and set to 5 it doesn't seem to be working and does not log off after 5 minutes.

I double checked that the environment variable is working by running echo %AUTOLOGOFF_NB_IDLE_MINUTES% in the command prompt which bring me back the value of 5.

Am I doing something wrong? Tried in both Win 7 and 2012 R2. Thanks.

**Comment by lcoulet** [comment]
Hi,
Did you define the environment variable in the SYSTEM scope? 
The code explicitly asks for the environment variable in the "Machine" target which should be SYSTEM, but maybe it requires elevated privileges.  I will have a look.

**Comment by AshleyHow** [comment]
Hi,

Yes I ensured that it was created in the system scope. Thank you for looking into this.

**Comment by lcoulet** [comment]
Hi, I could reproduce the issue on my PC. Modifying the scope for accessing the variable seems to have fixed the issue. 
Could you please test version 1.1? 
https://github.com/lcoulet/windows_AutoLogoff/releases/tag/1.1

**Comment by AshleyHow** [comment]
Hello,

Thank you it works perfect now!
